// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-dashboard/Bold.tsx": () => import("../components/mockups/admin-dashboard/Bold.tsx"),
  "./components/mockups/admin-dashboard/Current.tsx": () => import("../components/mockups/admin-dashboard/Current.tsx"),
  "./components/mockups/admin-dashboard/Dark.tsx": () => import("../components/mockups/admin-dashboard/Dark.tsx"),
  "./components/mockups/admin-dashboard/Modern.tsx": () => import("../components/mockups/admin-dashboard/Modern.tsx"),
  "./components/mockups/jo-driver/VariantA.tsx": () => import("../components/mockups/jo-driver/VariantA.tsx"),
  "./components/mockups/jo-driver/VariantB.tsx": () => import("../components/mockups/jo-driver/VariantB.tsx"),
  "./components/mockups/jo-driver/VariantC.tsx": () => import("../components/mockups/jo-driver/VariantC.tsx")
};
